name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: build with Gradle Wrapper
      working-directory: ./Opdracht6
      run: ./gradlew build

    - name: test with Gradle Wrapper
      working-directory: ./Opdracht6
      run: ./gradlew test
